/**
 * `npm run counts` — record what the suite actually contains, so the README can cite it.
 *
 * The README's test numbers have drifted in every review round, and the first attempt to pin them
 * counted `it(` occurrences with a regex. That was wrong twice over: it under-counts tests generated
 * in a loop (one `it(` producing four cases) and over-counts anything that merely looks like a call.
 * A checker that is itself unreliable is worse than none, because it fails for reasons that have
 * nothing to do with the thing it is guarding.
 *
 * So the count comes from vitest, which is the only component that knows. This writes
 * `tests/counts.json`, `tests/claims.test.ts` asserts the README against it, and CI regenerates it
 * and fails if the file is dirty — so the chain reality -> counts.json -> README cannot go stale
 * without something going red.
 *
 * Two runs, because the README documents two numbers a reader can reproduce: the clean-clone output
 * with no database, and the full total against a reachable cluster.
 */
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

type Totals = { total: number; passed: number; skipped: number; failed: number }

/** Runs the suite once and reads the machine-readable summary rather than scraping stdout. */
function measure(env: Record<string, string | undefined>): Totals {
  const dir = mkdtempSync(join(tmpdir(), 'sleeper-counts-'))
  const out = join(dir, 'result.json')
  try {
    try {
      execFileSync(
        'npx',
        ['vitest', 'run', '--reporter=json', `--outputFile=${out}`],
        // A failing suite still produces a report, and the counts are what we came for — a
        // non-zero exit here is not a reason to abandon the measurement.
        { stdio: 'ignore', env: { ...process.env, ...env } },
      )
    } catch {
      /* fall through to reading the report */
    }
    const r = JSON.parse(readFileSync(out, 'utf8')) as {
      numTotalTests: number
      numPassedTests: number
      numPendingTests: number
      numFailedTests: number
    }
    return {
      total: r.numTotalTests,
      passed: r.numPassedTests,
      skipped: r.numPendingTests,
      failed: r.numFailedTests,
    }
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
}

const LOCAL = 'postgresql://root@localhost:26257/sleeper?sslmode=disable'

console.log('measuring against a reachable cluster…')
const live = measure({ DATABASE_URL: LOCAL, SLEEPER_OFFLINE: '1' })

console.log('measuring a clean clone (no database)…')
// DATABASE_URL blanked rather than deleted: src/config.ts imports dotenv/config, so an unset var is
// immediately repopulated from .env and the "clean clone" measurement would silently be a live one.
const clean = measure({ DATABASE_URL: '', SLEEPER_OFFLINE: '1' })

if (live.total !== clean.total) {
  throw new Error(
    `the two runs disagree on the suite size (${live.total} vs ${clean.total}); ` +
      'a test is being registered conditionally on DATABASE_URL rather than skipped, ' +
      'which makes the documented numbers unreproducible',
  )
}

const counts = {
  total: live.total,
  cleanClone: { passed: clean.passed + clean.failed, skipped: clean.skipped },
  note:
    'Generated by `npm run counts`. cleanClone.passed folds in any failure so the figure describes ' +
    'the suite rather than the moment: a README count assertion failing here would otherwise ' +
    'deflate the number it is about to fix.',
}

writeFileSync('tests/counts.json', `${JSON.stringify(counts, null, 2)}\n`)
console.log(`\ntotal ${counts.total}`)
console.log(`clean clone: ${counts.cleanClone.passed} passed | ${counts.cleanClone.skipped} skipped`)
console.log('wrote tests/counts.json')
